eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8011/eureka/,http://localhost:8012/eureka/,http://localhost:8013/eureka/
spring:
  datasource:
    url: jdbc:mysql://10.250.250.230:3306/banco?useOldAliasMetadataBehavior=true&noAccessToProcedureBodies=true&useUnicode=yes&characterEncoding=utf8
    username: banco
    password: cascade25_09x
    driver-class-name: com.mysql.jdbc.Driver
