server:
  port: ${PORT:${SERVER_PORT:0}}
spring:
  datasource:
    url: jdbc:mysql://172.20.3.121:5001/amortizacion?useOldAliasMetadataBehavior=true&noAccessToProcedureBodies=true&useUnicode=yes&characterEncoding=utf8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
