server:
  port: 7777
spring:
  datasource:
    url: jdbc:mysql://172.20.3.121:5000/operacion?useOldAliasMetadataBehavior=true&noAccessToProcedureBodies=true&useUnicode=yes&characterEncoding=utf8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
